apiVersion: v1
kind: Pod
metadata:
  namespace: demo-pods
  labels:
    run: invalid-image
  name: invalid-image
spec:
  containers:
  - image: traefik
    name: traefik-image
    securityContext:
      privileged: true