apiVersion: v1
kind: Pod
metadata:
  labels:
    run: missing-ipp
  name: missing-ipp
spec:
  containers:
  - image: nginx:latest
    name: missing-ipp
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL
