apiVersion: v1
kind: Pod
metadata:
  namespace: demo-pods
  labels:
    run: failing-demo
    tech-lead: someone
  name: valid-tech-lead-demo
spec:
  containers:
  - image: nginx
    name: failing-demo
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL