name: Kyverno Tests

on:
    - push
    - workflow_dispatch

jobs:
  kyverno-job:
    runs-on: ubuntu-latest
    name: Run kyverno
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate policy
        uses: gbaeke/kyverno-cli@v1
        with:
          command: |
            kyverno test .